#Daniel Khomyakov y Raul Martinez Llorente

apiVersion: v1
kind: Service
metadata:
 name: multmatrix-service
 namespace: default
spec:
 type: NodePort
 selector:
   app: multmatrix
 clusterIP: 10.100.218.213
 ports:
 - port: 3301
   targetPort: 3301
   nodePort: 31001
 externalTrafficPolicy: Cluster
